# Generated by Django 3.2.8 on 2021-10-08 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(help_text='Cafe ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product/')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('price', models.IntegerField()),
                ('isSoldOut', models.BooleanField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='cafeapp.cafe')),
            ],
        ),
    ]
