# Generated by Django 3.2.8 on 2021-10-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
